apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bluespice.fullname" . }}-wiki-config
  namespace: {{ default "default" $.Release.Namespace }}
  labels:
    {{- include "bluespice.labels" . | nindent 4 }}
data:
  VERSION: {{ default "" .Values.wikiEnv.configEnv.VERSION | quote }}
  EDITION: {{ required "wikiEnv.configEnv.EDITION is required" .Values.wikiEnv.configEnv.EDITION | quote }}
  WIKI_NAME: {{ required "wikiEnv.configEnv.WIKI_NAME is required" .Values.wikiEnv.configEnv.WIKI_NAME | quote }}
  WIKI_LANG: {{ required "wikiEnv.configEnv.WIKI_LANG is required" .Values.wikiEnv.configEnv.WIKI_LANG | quote }}
  WIKI_PASSWORDSENDER: {{ default "" .Values.wikiEnv.configEnv.WIKI_PASSWORDSENDER | quote }}
  WIKI_EMERGENCYCONTACT: {{ default "" .Values.wikiEnv.configEnv.WIKI_EMERGENCYCONTACT | quote }}
  WIKI_HOST: {{ required "wikiEnv.configEnv.WIKI_HOST is required" .Values.wikiEnv.configEnv.WIKI_HOST | quote }}
  WIKI_PORT: {{ required "wikiEnv.configEnv.WIKI_PORT is required" .Values.wikiEnv.configEnv.WIKI_PORT | quote }}
  WIKI_PROTOCOL: {{ required "wikiEnv.configEnv.WIKI_PROTOCOL is required" .Values.wikiEnv.configEnv.WIKI_PROTOCOL | quote }}
  WIKI_INITIAL_ADMIN_PASS: {{ default "" .Values.wikiEnv.configEnv.WIKI_INITIAL_ADMIN_PASS | quote }}
  WIKI_INITIAL_ADMIN_USER: {{ default "" .Values.wikiEnv.configEnv.WIKI_INITIAL_ADMIN_USER | quote }}
  WIKI_SUBSCRIPTION_KEY: {{ default "" .Values.wikiEnv.configEnv.WIKI_SUBSCRIPTION_KEY | quote }}
  DB_USER: {{ required "wikiEnv.configEnv.DB_USER is required" .Values.wikiEnv.configEnv.DB_USER | quote }}
  DB_HOST: {{ required "wikiEnv.configEnv.DB_HOST is required" .Values.wikiEnv.configEnv.DB_HOST | quote }}
  DB_NAME: {{ required "wikiEnv.configEnv.DB_NAME is required" .Values.wikiEnv.configEnv.DB_NAME | quote }}
  DB_PREFIX: {{ default "" .Values.wikiEnv.configEnv.DB_PREFIX | quote }}
  SMTP_HOST: {{ default "" .Values.wikiEnv.configEnv.SMTP_HOST | quote }}
  SMTP_PORT: {{ default "" .Values.wikiEnv.configEnv.SMTP_PORT | quote }}
  SMTP_USER: {{ default "" .Values.wikiEnv.configEnv.SMTP_USER | quote }}
  SMTP_PASS: {{ default "" .Values.wikiEnv.configEnv.SMTP_PASS | quote }}
  SMTP_ID_HOST: {{ default "" .Values.wikiEnv.configEnv.SMTP_ID_HOST | quote }}
  SEARCH_HOST: {{ default "" .Values.wikiEnv.configEnv.SEARCH_HOST | quote }}
  SEARCH_PORT: {{ default "" .Values.wikiEnv.configEnv.SEARCH_PORT | quote }}
  SEARCH_PROTOCOL: {{ default "" .Values.wikiEnv.configEnv.SEARCH_PROTOCOL | quote }}
  SEARCH_USER: {{ default "" .Values.wikiEnv.configEnv.SEARCH_USER | quote }}
