{{- range $key, $value := .Values.statelessbackendServices }}
{{- $collabpadsDbEnabled := and (eq $value.name "collabpads") (and $.Values.statefulBackendServices $.Values.statefulBackendServices.collabpadsDatabase $.Values.statefulBackendServices.collabpadsDatabase.enabled) }}
{{- if $value.configEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bluespice.fullname" $ }}-{{ $value.name }}-config
  namespace: {{ default "default" $.Release.Namespace }}
  labels:
    app: {{ $value.name }}
    {{- include "bluespice.labels" $ | nindent 4 }}
data:
  {{- range $envKey, $envValue := $value.configEnv }}
  {{ $envKey }}: {{ $envValue | quote }}
  {{- end }}
---
{{- end }}
{{- if and (not $collabpadsDbEnabled) (not (and $value.existingSecret $value.existingSecret.name)) $value.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bluespice.fullname" $ }}-{{ $value.name }}-secret
  namespace: {{ default "default" $.Release.Namespace }}
  labels:
    app: {{ $value.name }}
    {{- include "bluespice.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $envKey, $envValue := $value.secretEnv }}
  {{ $envKey }}: {{ $envValue | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
