{{- $wikiWeb := default (dict) (index .Values.wikiServices "wiki-web") }}
{{- if and $wikiWeb.hpa $wikiWeb.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-hpa" $wikiWeb.name }}
  namespace: {{ default "default" .Release.Namespace }}
  labels:
    app: {{ $wikiWeb.name }}
    {{- include "bluespice.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $wikiWeb.name }}
  minReplicas: {{ default 1 $wikiWeb.hpa.minReplicas }}
  maxReplicas: {{ default 3 $wikiWeb.hpa.maxReplicas }}
  metrics:
    {{- toYaml $wikiWeb.hpa.metrics | nindent 4 }}
  {{- with $wikiWeb.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
