{{- if $.Values.statefulBackendServices.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: bluespice-database-secrets
  namespace: {{ default "default" $.Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: {{ $.Values.statefulBackendServices.database.secrets.MARIADB_ROOT_PASSWORD | b64enc | quote }}
  MARIADB_PASSWORD: {{ $.Values.statefulBackendServices.database.secrets.MARIADB_PASSWORD | b64enc | quote }}
{{- end }}
