#!/bin/bash
source .env

if [ ! -d ${DATADIR} ];then
echo "Creating Persistent-Data-Directories"
mkdir -p ${DATADIR}/search/data/nodes/0
mkdir -p ${DATADIR}/wiki
mkdir -p ${DATADIR}/proxy
mkdir -p ${DATADIR}/database
mkdir -p ${DATADIR}/database-collabpads
sudo chown -R 1000:1000 ${DATADIR}/search
sudo chown -R 1002:1002 ${DATADIR}/wiki
fi

docker compose \
	-f docker-compose.main.yml \
	-f docker-compose.persistent-data-services.yml \
	-f docker-compose.stateless-services.yml \
	-f docker-compose.proxy.yml \
	$@

