#!/bin/bash

source .env
EXTENDED_TOOLS=""


if [ "${EDITION}" == "pro" || "${EDITION}" == "farm" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.collabpads-service.yml"
	BLUESPICE_REPOSITORY=docker.bluespice.com/bluespice-${EDITION}/wiki:${VERSION}
else
	BLUESPICE_REPOSITORY=bluespice/wiki:${VERSION}
fi
if [ "${LETSENCRYPT}" == "true" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.proxy-letsencrypt.yml"
fi
if [ "${KERBEROS}" == "true" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.kerberos-proxy.yml"
fi
	docker compose \
		-f docker-compose.main.yml \
		-f docker-compose.persistent-data-services.yml \
		-f docker-compose.stateless-services.yml \
		-f docker-compose.proxy.yml \
		${EXTENDED_TOOLS} \
		$@
