#!/bin/bash

source .env
EXTENDED_TOOLS=""


if [[ "${EDITION}" == "pro" || "${EDITION}" == "farm" ]]; then
	if [[ ! $(grep 'docker.bluespice.com' $HOME/.docker/config.json) ]]; then 
		echo "In order to access our ${EDITION}-Image please login to docker.bluespice.com"
		docker login docker.bluespice.com
		if [[ ! $(grep 'docker.bluespice.com' $HOME/.docker/config.json) ]]; then 
		echo -e "\n-------------\n"
		echo "Please contact support@hallowelt.com for your Credentials against docker.bluespice.com"
		echo -e "\n-------------\n"
		exit
		fi
	fi
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.collabpads-service.yml"
	REPO=docker.bluespice.com/bluespice-${EDITION}/wiki:${VERSION}
else
	REPO=bluespice/wiki:${VERSION}
fi
if [ "${LETSENCRYPT}" == "true" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.proxy-letsencrypt.yml"
fi
if [ "${KERBEROS}" == "true" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.kerberos-proxy.yml"
else
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.proxy.yml"
fi
	BLUESPICE_REPOSITORY=${REPO} \
		docker compose \
		-f docker-compose.main.yml \
		-f docker-compose.persistent-data-services.yml \
		-f docker-compose.stateless-services.yml \
		${EXTENDED_TOOLS} \
		$@
