services:

  statisticsdashboard:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/statisticsdashboard:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME:-bluespice}-statisticsdashboard
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PATH: ${WIKI_BASE_PATH:-/}_statisticsdashboard/
      VIRTUAL_PORT: 3000
      VIRTUAL_DEST: /
      GF_SERVER_ROOT_URL: https://${WIKI_HOST}${WIKI_BASE_PATH:-/}_statisticsdashboard/
      GF_SERVER_PROTOCOL: http
      GF_SERVER_DOMAIN: ${WIKI_HOST}
    volumes:
      - ${DATADIR}/statistics-dashboard/data:/var/lib/grafana
